include: "rules/common.smk"
include: "rules/convert.smk"
include: "rules/derep.smk"
include: "rules/swarm.smk"


(SAMPLES,) = glob_wildcards("reads/final/{sample}.fastq")


rule all:
    input:
        expand("reads/final/{sample}.swarm_stats_pretty.tsv", sample=SAMPLES),
    output:
        "data/swarm_stats.tsv",
    shell:
        """
        qsv cat rowskey --group fstem --group-name sample --output {output} {input}
        sed -i "s/\\.swarm_stats_pretty//" {output}
        """
